### ISSUE TITLE
Create Frontend Project

### ISSUE THREAD

**Issue by ArastoSahbaei** [ArastoSahbaei/CommunityRatesGames#14]
create angular-cli
- [ ] Use Service class for all HTTP calls
- [ ] HTTP interceptor for headers in http calls
- [ ] Use Router to link together all front end parts
- [ ] Use loginview to determine which links to show. (Lazy Loading)

**Comment by BKristenssonAlfsson** [comment]
Vi tar denna nästa spring när vi alla har en front för våra backend bitar så får någon bygga ihop alla front ends till en SPA eller något

**Comment by ArastoSahbaei** [comment]
låter bra
