### ISSUE TITLE
Refactor to remove Lombok

### ISSUE THREAD

**Issue by ArastoSahbaei** [ArastoSahbaei/CommunityRatesGames#28]

**Comment by ArastoSahbaei** [comment]
also remove from pom.xml

**Comment by Hanicef** [comment]
well, ive already done this, as it gave me serious issues in my latest pr: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#lombok
so only a change in the pom.xml is all that is needed now (sorry, @Ivefan ).
