### ISSUE TITLE
Entity: Platform

### ISSUE THREAD

**Issue by ArastoSahbaei** [ArastoSahbaei/CommunityRatesGames#7]
Columns:
• Id
• Name
• Release Year
- [x] Create entity
- [x] Create repository
- [ ] Assign foreign key to Company table
- [ ] Assign foreign key to Game table
- [x] Create service

**Comment by Swesson92** [comment]
Även lägga till tillverkare av consol

**Comment by ArastoSahbaei** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5bd86ee91fc3b8000f7ad1e9/attachments/5bdaea471fc3b8000f7ba9f8)
